- docker-compose.integration-test.yml
- docker-compose.yml
add notfication service to general docker-compose file and fix duplicate in integrations tests
> add notification service and fix duplicate in integrations tests

- docker-compose.end-to-end-tests.yml
- docker-compose.integration-test.yml
This PR switches the docker for integartion test for the lern-store from legacy to edu-sharing.
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6690
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/1795
- https://github.com/hpi-schul-cloud/end-to-end-tests/pull/217
> SC-6690 - Lernstore env vars

- CHANGELOG.md
- docker-compose.integration-test.yml
If the fallback docker compose script if used, the old volume path for the notification service should be used.
> SC-7638 Change volume path for notification service

- .github/wordflows/test.yml
add integration tests to get noticed if changes crash the tests
> add integration tests to get noticed if changes crashed the tests

- .github/workflows/test.yml
remove if release condition from tests
> run everytime something changed

- docker-compose.integration-test.yml
> cleanup merge changes

- CHANGELOG.md
- scripts/dockerhub.login.sh
added docker login helper for https://ticketsystem.hpi-schul-cloud.org/browse/SC-8356 to be used by client/server mocha tests
> SC-8356 add docker login helper

- compose-files/docker-compose.yml
- scripts/mongo_setup.sh
use a mongo replica set instead of a single node to get closer to live enviremnet
> add mongodb replica set

- startup_end-to-end-tests.sh
> SC-8837 fix e2e env loading

- compose-files/docker-compose.dev.yml
- compose-files/docker-compose.file.yml
- compose-files/docker-compose.superhero.yml
- envs/develop.env
Improve some stuff which pops up while using it
> improvements and fixes

- docker-compose.end-to-end-tests-Build.yml
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2614
> Add rabbitMq as server dependency

- compose-files/docker-compose.yml
> add maildrop with mailcatcher support

- compose-files/docker-compose.end-to-end-tests.yml
- compose-files/docker-compose.yml
- docker-compose.end-to-end-tests-Build.yml
- startup_end-to-end-tests.sh
Fix the scripts to run the e2e test and update dthe docker files
https://ticketsystem.hpi-schul-cloud.org/browse/BC-66
Fix the scripts to run the e2e test and update dthe docker files
> BC-66 - fix scriptes and docker compose files

- .github/workflows/test.yml
- CHANGELOG.md
- compose-files/docker-compose.yml
This PR adds a new service server management based on server image.
It starts the servers management api to be used in e2e tests for database seeding.
- https://ticketsystem.schul-cloud.org/browse/BC-25
- https://github.com/hpi-schul-cloud/end-to-end-tests/pull/352
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/2961/
> BC-25 add server management service

- compose-files/docker-compose.yml
- docker-compose.end-to-end-tests-Build.yml
> add LDAP_PASSWORD_ENCRYPTION_KEY

- compose-files/docker-compose.yml
- docker-compose.end-to-end-tests-Build.yml
Exchanged LDAP_PASSWORD_ENCRYPTION_KEY for AES_KEY to decrypt then oauth client secret. It's just a name change.
Please merge together with the Server PR
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3330
[N21-36](https://ticketsystem.hpi-schul-cloud.org/browse/N21-36)
> exchanged LDAP_PASSWORD_ENCRYPTION_KEY for AES_KEY

- README.md
Declaring of depreciation for the docker compose files for this project
> Declaring of depreciation for the docker compose files for this project

- compose-files/docker-compose.superhero.yml
- compose-files/docker-compose.yml
- docker-compose.end-to-end-tests-Build.yml
- docker-compose.integration-test-Build.yml
> BC-1500 rename BACKEND_URL

- compose-files/docker-compose.yml
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3500
https://github.com/hpi-schul-cloud/docker-compose/pull/55
> BC-1622 Add missing env, that server can be started.

- .github/workflows/test.yml
> updated gh-actions

- compose-files/docker-compose.yml
- envs/end-to-end-tests.env
> BC-2674 - Nuxt removal

- compose-files/docker-compose.yml
- docker-compose.end-to-end-tests-Build.yml
- docker-compose.integration-test-Build.yml
Adds FWU_CONTENT__S3_ENDPOINT, FWU_CONTENT__S3_ACCESS_KEY, FWU_CONTENT__S3_SECRET_KEY, FWU_CONTENT__S3_BUCKET and FWU_CONTENT__S3_REGION for tests.
Tickets:
https://ticketsystem.dbildungscloud.de/browse/BRB-200
https://ticketsystem.dbildungscloud.de/browse/BRB-187
Epic:
https://ticketsystem.dbildungscloud.de/browse/BRB-181
Initiative:
https://ticketsystem.dbildungscloud.de/browse/BRB-178
Documentation:
https://docs.dbildungscloud.de/display/DBH/Technical+documentation+-+FWU+content+in+the+Learn-Store
PR dof app deploy:
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/485
PR schulcloud server:
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3975
> Brb 181 fwu routing

- compose-files/docker-compose.yml
Change is needed for legacy e2e tests to run successfully on nuxt client
https://github.com/hpi-schul-cloud/nuxt-client/pull/2748
> Thr 18 dev feature h5p editor
